:sparkles: adding lottery section
interest-protocol/burrrd-website pull request #46
Opened 2024-01-18 01:41 UTC by KipandaJr

About the name of icons like `First, Second and Others`plz suggest other names or ignore this approach
@git-marcopitra @atilasousa @MarioBatalha

2024-01-18 20:52 UTC, git-marcopitra requested changes
The name suggestion is object name or objective name

2024-01-23 16:15 UTC, MarioBatalha requested changes

2024-01-23 16:15 UTC, MarioBatalha commented on views/home/lottery/index.tsx
> +    <Box variant="container" mx="auto" id="lottery" bg="#1B1622" py="3rem">
You need to check the height in the way that the section fill the entire viewport aside of the coin address section.

2024-01-23 16:15 UTC, MarioBatalha commented on views/home/lottery/index.tsx
> +                p={[
Please check the padding, mainly px cuz it's not the same as on Figma

2024-01-23 16:20 UTC, KipandaJr commented on views/home/lottery/index.tsx
> +    <Box variant="container" mx="auto" id="lottery" bg="#1B1622" py="3rem">
Burrrd for the time being you don't have to worry about being faithful to the LIB theme, you can skip these checks in BURRRD

2024-01-23 16:20 UTC, KipandaJr commented on views/home/lottery/index.tsx
> +                p={[
Burrrd for the time being you don't have to worry about being faithful to the LIB theme, you can skip these checks in BURRRD

2024-01-25 19:39 UTC, git-marcopitra requested changes

2024-01-25 19:39 UTC, git-marcopitra commented on views/home/lottery/index.tsx
> +  return (
remove the return

2024-01-25 19:39 UTC, git-marcopitra commented on views/home/lottery/illustraction/coins/coin-wrapper.tsx
> +  const delay = 0.5;
To have different timings on floating u can use `Math.random()` for the `delay` and `duration`

2024-01-25 19:44 UTC, git-marcopitra commented
@KipandaJr write on the button "COMING SOON"

2024-01-26 20:16 UTC, MarioBatalha approved these changes

2024-01-28 01:13 UTC, git-marcopitra approved these changes

2024-01-28 01:13 UTC, merged