:sparkles: new partners section added
interest-protocol/burrrd-website pull request #48
Opened 2024-01-23 19:03 UTC by KipandaJr

2024-01-24 08:45 UTC, MarioBatalha commented on public/images/partners/gotbit.png
Image format must be svg or webp.

2024-01-24 08:45 UTC, MarioBatalha commented on public/images/partners/stoned-ape-crew.png
Image format must be svg or webp.

2024-01-24 08:45 UTC, MarioBatalha commented on public/images/partners/zebec.png
Image format must be svg or webp.

2024-01-24 08:48 UTC, MarioBatalha commented on views/home/partners/title.tsx
> +      <HandsSVG maxHeight="100%" maxWidth="100%" width="100%" height="60%" />
Is missing hand-waving animation

2024-01-24 08:48 UTC, MarioBatalha commented on public/images/partners/zebec.png
Check if this image can be in svg or webp

2024-01-24 08:54 UTC, MarioBatalha requested changes

2024-01-26 20:09 UTC, MarioBatalha requested changes

2024-01-26 20:09 UTC, MarioBatalha commented on views/home/partners/title.tsx
> +    <Motion
It's not the right animation, look for waving hand animation.

2024-01-29 04:43 UTC, git-marcopitra approved these changes

2024-01-29 04:43 UTC, merged