feat: add new UI
interest-protocol/burrrd-website pull request #51
Opened 2024-01-25 18:18 UTC by MarioBatalha

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206412086603101

2024-01-25 19:32 UTC, KipandaJr requested changes
<img width="402" alt="image" src="https://github.com/interest-protocol/burrrd-website/assets/34079870/fca9e114-ff1e-46e5-a4e6-ac3db1bc6aad">
 check the mobile version

<img width="342" alt="image" src="https://github.com/interest-protocol/burrrd-website/assets/34079870/7255d434-b722-44f7-86d8-79278d921222">

<img width="283" alt="image" src="https://github.com/interest-protocol/burrrd-website/assets/34079870/526ffe7f-7aa1-4bda-93c4-f478e5fb75b2">

2024-01-25 19:32 UTC, KipandaJr commented on views/home/hero/index.tsx
> +              fontSize="14px"
`rem`instead `px`

2024-01-25 19:32 UTC, KipandaJr commented on views/home/hero/index.tsx
> +              lineHeight="20px"
`rem`instead `px`

2024-01-25 19:32 UTC, KipandaJr commented on views/home/hero/index.tsx
> +              fontSize="14px"
`rem`instead `px`

2024-01-28 01:16 UTC, git-marcopitra approved these changes

2024-01-28 01:17 UTC, merged