:sparkles: feat: ambassors section added
interest-protocol/burrrd-website pull request #53
Opened 2024-01-28 23:13 UTC by atilasousa

2024-01-29 00:53 UTC, KipandaJr requested changes

2024-01-29 00:53 UTC, KipandaJr commented on views/home/ambassors/index.tsx
see how we do this on `TopBar`, we need a `Slider` dont this behavior

2024-01-29 11:44 UTC, MarioBatalha requested changes

2024-01-29 22:33 UTC, KipandaJr requested changes

2024-01-29 22:33 UTC, KipandaJr commented on views/home/ambassors/index.tsx
> +    },
On settings plz add the `infinite: true`

2024-01-29 22:33 UTC, KipandaJr commented on views/home/ambassors/index.tsx
> +        <Controllers handleNext={handleNext} handlePrevious={handlePrevious} />
check well if this Controllers r working well cuz here i have a weird behavior

2024-01-29 22:33 UTC, KipandaJr commented on views/home/ambassors/index.tsx
> +  const sliderResponsiviness = [
Put this on another file `ambassors.data.ts`

2024-01-30 15:14 UTC, git-marcopitra requested changes

2024-01-30 15:14 UTC, git-marcopitra commented on views/home/ambassors/controllers/index.tsx
> +interface ControllersProps {
move it to `.types` file

2024-01-30 15:14 UTC, git-marcopitra commented on views/home/ambassors/index.tsx
> +        slidesToScroll: 3,
slidesToScroll must be always 1

2024-02-01 07:38 UTC, KipandaJr requested changes
![image](https://github.com/interest-protocol/burrrd-website/assets/34079870/f910e896-fbb8-49ff-bbcb-7d92e8511fcc)
the padding on mobile card r weird, plz check

2024-02-01 20:55 UTC, MarioBatalha approved these changes

2024-02-01 21:02 UTC, KipandaJr requested changes

2024-02-01 21:02 UTC, KipandaJr commented on views/home/index.tsx
> +import Ambassors from './ambassadors';
Change `Ambassors` to `Ambassadors`

2024-02-02 03:00 UTC, git-marcopitra approved these changes

2024-02-03 22:57 UTC, merged