🎇  Add new gradient to roadmap and disclaimer section
interest-protocol/burrrd-website pull request #55
Opened 2024-01-29 12:43 UTC by MarioBatalha

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206412083694643

2024-01-29 19:55 UTC, KipandaJr requested changes
Solve the conflits on this PR

2024-01-30 20:14 UTC, atilasousa approved these changes

2024-01-30 20:36 UTC, git-marcopitra approved these changes

2024-01-30 20:58 UTC, git-marcopitra approved these changes

2024-01-30 21:07 UTC, KipandaJr requested changes
![image](https://github.com/interest-protocol/burrrd-website/assets/34079870/fc848126-897b-4529-b71c-5cc221f97424)
check this gradient

2024-01-31 20:13 UTC, KipandaJr requested changes
![image](https://github.com/interest-protocol/burrrd-website/assets/34079870/fb031c90-550b-4330-b607-0ee45b9be95a)

see this line on top to disclaimer section


![image](https://github.com/interest-protocol/burrrd-website/assets/34079870/262c2875-de7f-4d00-b249-f0a5496af32b)

2024-02-01 12:54 UTC, atilasousa approved these changes

2024-02-01 19:57 UTC, KipandaJr approved these changes

2024-02-01 20:05 UTC, git-marcopitra approved these changes

2024-02-01 20:06 UTC, merged