✨  Add new tokenomics UI
interest-protocol/burrrd-website pull request #56
Opened 2024-01-29 14:03 UTC by MarioBatalha

2024-01-29 20:03 UTC, KipandaJr requested changes
In general the this 
![image](https://github.com/interest-protocol/burrrd-website/assets/34079870/e3d6ae49-c5a9-4335-acff-9df20a8b89f2)
 dosent look equal that figma 
![image](https://github.com/interest-protocol/burrrd-website/assets/34079870/7067e6af-157e-4158-b184-226cfd9e1625)

2024-01-30 14:44 UTC, git-marcopitra requested changes

2024-01-30 14:44 UTC, git-marcopitra commented on components/svg/dex-screener.tsx
>  const DexScreener: FC<SVGProps> = ({ maxHeight, maxWidth, ...props }) => (
this changes are out of the scope, and doesn't make sense

2024-01-30 20:17 UTC, KipandaJr requested changes
![image](https://github.com/interest-protocol/burrrd-website/assets/34079870/ad7c17e0-35e8-4630-a2d8-9c327c18f347)

2024-02-01 04:59 UTC, git-marcopitra approved these changes

2024-02-01 21:30 UTC, git-marcopitra requested changes

2024-02-01 21:30 UTC, git-marcopitra commented on components/layout/footer/index.tsx
> +      "
why do we have this `;`

2024-02-01 21:30 UTC, git-marcopitra commented on views/home/index.tsx
> +import DisclaimerSection from './disclaimer-section';
don't use the suffix `Section` on files, neither on the components

2024-02-01 21:35 UTC, atilasousa approved these changes

2024-02-02 02:24 UTC, git-marcopitra approved these changes

2024-02-03 22:56 UTC, merged